version: "3.9"
services:
  back-app:
    platform: linux/x86_64
    container_name: back-app
    image: prod/docker-nest-app
    build: .
    ports:
      - "3000:3000"
    tty: true
    command: sh -c "node dist/main.js"
